### request first incident
http://localhost:80/incidents/3c234027-4b51-4f5f-89f5-b7a11be77db0


### update first incident
PATCH  http://localhost/incidents/3c234027-4b51-4f5f-89f5-b7a11be77db0
Content-Type: application/json

{
  "description": "Look at this new description Mr Drop Table "
}
