version: '3'

services:
  api:
    image: codfish/json-server:0.17.3
    ports:
      - 9999:80
    volumes:
      - ./data/db.json:/app/db.json:delegated
#    environment:
#      VIRTUAL_HOST: typescript.json-server.docker