controller:
  config:
    enable-modsecurity: "true"
    enable-owasp-modsecurity-crs: "true"
    modsecurity-snippet: |
      Include /etc/nginx/modsecurity/custom-rules.conf
  extraVolumeMounts:
    - name: modsecurity-rules
      mountPath: /etc/nginx/modsecurity/custom-rules.conf
      subPath: custom-rules.conf
  extraVolumes:
    - name: modsecurity-rules
      configMap:
        name: modsecurity-rules
