apiVersion: v1
kind: ConfigMap
metadata:
  name: modsecurity-rules
  namespace: ingress-nginx
data:
  # Custom ModSecurity rules for exceptions
  custom-rules.conf: |
    # Allow specific endpoints without WAF inspection
    SecRule REQUEST_URI "@beginsWith /api/health" \
      "id:1000,\
      phase:1,\
      pass,\
      nolog,\
      ctl:ruleEngine=Off"

    # Exclude specific rules for /incidents endpoint
    SecRule REQUEST_URI "@beginsWith /incidents" \
      "id:1001,\
      phase:1,\
      pass,\
      nolog,\
      ctl:ruleRemoveById=920350,\  # Prevent rule blocking valid JSON
      ctl:ruleRemoveById=942100-942999,\  # SQL Injection rules
      ctl:ruleRemoveById=933100-933999"   # PHP Injection rules

    # Allow larger request bodies for specific endpoints
    SecRule REQUEST_URI "@beginsWith /incidents" \
      "id:1002,\
      phase:1,\
      pass,\
      nolog,\
      setvar:tx.allowed_request_body_size=64000000"
