apiVersion: apps/v1
kind: Deployment
metadata:
  name: incidents-api
  namespace: incidents
  labels:
    app: incidents-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: incidents-api
  template:
    metadata:
      labels:
        app: incidents-api
    spec:
      containers:
        - name: json-server
          image: docker.io/bitsls2/json-server:latest
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "200m"
              memory: "128Mi"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: data
              mountPath: /app
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: incidents-data-pvc
