apiVersion: apps/v1
kind: Deployment
metadata:
  name: albedo
  namespace: incidents
  labels:
    app: albedo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: albedo
  template:
    metadata:
      labels:
        app: albedo
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: albedo
          image: ghcr.io/coreruleset/albedo:0.2.0
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "200m"
              memory: "128Mi"
            requests:
              cpu: "100m"
              memory: "64Mi"
